on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install gettext on macos
        if: matrix.os == 'macos-latest'
        run: |
            brew install gettext
            brew link --force gettext

            sudo mkdir -p /usr/local/libodep/lib
            sudo ln -s /opt/local/lib/libintl.8.dylib /usr/local/libodep/lib/libintl.8.dylib
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
        
      - name: Install Dependencies
        run: |
            pip install -r requirements.txt

      - name: Build Executable
        run: |
            nuitka --follow-imports --standalone --onefile --output-dir=export --include-plugin-directory=system --plugin-enable=pyqt6 singularity-qt.py d
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }} Build
            path: |
                build/*.exe
                build/*.bin
                build/*.app/**/*
            include-hidden-files: true