on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install gettext on macos
        if: matrix.os == 'macos-latest'
        run: |
            brew install gettext
            brew link --force gettext

            sudo mkdir -p /usr/local/libodep/lib
            sudo ln -s /opt/local/lib/libintl.8.dylib /usr/local/libodep/lib/libintl.8.dylib
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
        
      - name: Install Dependencies
        run: |
            pip install -r requirements.txt

      - name: Install depends on Windows
        if: runner.os == 'Windows'
        run: |
            mkdir -p C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64
            curl -L -o C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64\depends.zip https://dependencywalker.com/depends22_x64.zip
            tar -xf C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64\depends.zip -C C:\Users\RUNNER~1\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\depends\x86_64

      - name: Build Executable
        run: |
            nuitka --follow-imports --standalone --onefile --output-dir=build --include-plugin-directory=system --plugin-enable=pyqt6 singularity-qt.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }} Build
            path: |
                build/*.exe
                build/*.bin
                build/*.app/**/*
            include-hidden-files: true