on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install Python on macOS
        if: runner.os == 'macOS'
        run: |
            brew install python@3.10
            echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> ~/.zshrc
            source ~/.zshrc

      - name: Install Python on Ubuntu
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            sudo apt-get install python3.10 python3.10-venv python3.10-dev -y
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

      - name: Install Python on Windows
        if: runner.os == 'Windows'
        run: choco install python --version=3.10

      - name: Install Dependencies
        run: |
            pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
            nuitka-version: main
            script-name: kasa_cli
            mode: app
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }} Build
            path: |
                build/*.exe
                build/*.bin
                build/*.app/**/*
            include-hidden-files: true